---
title: "Bernoulli_Test"
author: "MBonitz, AKuras"
date: "28 November 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bernoulli Verteilung


```{r graph Darstellung}
#Data: eine wahre Aussage, zwei falsche
True <- 1
False <- 2

#Darstellung mehrer Plots auf einer Seite: prior, likelihood und posterior
par(mfrow = c(3,1))

#set prior and theta
prior <- c(0.25,0.25,0.25,0.25)
theta <- c(0.1,0.4,0.6,0.8)
#create data frame for x,y
prior_graph <- data.frame(theta,prior)
#plot of prior
plot((prior_graph),
     type = "h",
     main="Prior",
     xlim=c(0, 1), ylim=c(0, 0.6)
     )

#Bernoulli-Verteilung
likelihood <- c(prior^True*(1-prior)^False)
likelihood_graph <-data.frame(theta,likelihood)
plot ((likelihood_graph),
      type = "h",
      main="Likelihood",
      xlim=c(0, 1), ylim=c(0, 0.6)
      )

#Bayes´ Rule
posterior <- c((likelihood*prior)/((likelihood*prior)+((1-likelihood)*(1-prior))))
posterior_graph <-data.frame(theta,posterior)
plot((posterior_graph),
     type = "h",
     main="Posterior",
     xlim=c(0, 1), ylim=c(0, 0.6)
     )

```


