---
title: "Shiny App Hausaufgabe - Bayes'Theorem 27.11.2017"
author: "Pablo Kaiser"
date: "27 November 2017"
output: html_document
runtime: shiny
---
####**Bayes' Theorem**  

$$P(A|B)=P(B|A)*P(A)/P(B)$$
 
**P(A | B) ist die (bedingte) Wahrscheinlichkeit des Ereignisses A unter der Bedingung, dass B eingetreten ist**  
  
  
**P(B | A) ist die (bedingte) Wahrscheinlichkeit des Ereignisses B unter der Bedingung, dass A eingetreten ist**  

  **P(A) ist die Wahrscheinlichkeit (Anfangswahrscheinlichkeit) für das Eintreten des Ereignisses A**  
  
  **P(B) ist die Wahrscheinlichkeit (Anfangswahrscheinlichkeit) für das Eintreten des Ereignisses B**  
  
  
####**Erläuterung**  
  
    
*Der Satz von Bayes erlaubt das Umkehren und anschließende kalkulieren von bedingten Wahrscheinlichkeiten. Anfangswahrscheinlichkeitseinschätzungen werden durch Lerneffekte angepasst und somit auch die Ergebniswahrscheinlichkeit. Also ist das Lernen aus Erfahrung ein zentraler Anwendungsbereich.*  

```{r eruptions, echo=FALSE}
library(shiny)


ui <- fluidPage(
  titlePanel(h4("Bayes Interaktiv")
  ),
  sidebarLayout(
    sidebarPanel(
      helpText(strong("Bayes Rechenhilfe")),
                numericInput(inputId = "like",
                            label = "Likelihood P(B|A)",
                            value = 0.5, min = 0, max = 1, step = 0.01),
                numericInput(inputId = "Prior",
                             label = "Prior P(A)",
                             value = 0.5, min = 0, max = 1, step = 0.01),
  numericInput("PB","Anfangswahrscheinlichkeit P(B)",value = 0.5,min =0, max = 1, step = 0.01),
  actionButton("calc","Berechnen")
    ),
  
  mainPanel(textOutput("Ergebnis"),plotOutput("space")
    )
  )
)
  



server<- function(input, output){
  Button = eventReactive(input$calc, {(input$like*input$Prior)/(input$PB)
    })
  output$Ergebnis = renderText({paste("Die Wahrscheinlichkeit für P(A|B) ist", Button())
    })
}
shinyApp(ui = ui, server = server)
```
  
    
  **Gerne hätte ich zu der allgemeinen Rechnung noch die Beispielrechnung implementiert. Dazu wäre ein Wahrscheinlichkeitsdichte Plot von Posterior,Prior und Likelihood gut um deren Abhängigkeiten zu veranschaulichen.**